#
# Copyright (C) 2019 The Falco Authors.
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

####################
# Your custom rules!
####################

# Add new rules, like this one
# - rule: The program "sudo" is run in a container
#   desc: An event will trigger every time you run sudo in a container
#   condition: evt.type = execve and evt.dir=< and container.id != host and proc.name = sudo
#   output: "Sudo run in container (user=%user.name %container.info parent=%proc.pname cmdline=%proc.cmdline)"
#   priority: ERROR
#   tags: [users, container]

# Or override/append to any rule, macro, or list from the Default Rules
#
#

- rule: PHP-fpm do not use execve system call
  desc: An event will trigger every time you run sudo in a container
  condition: evt.type = execve and evt.dir=< and container.id != host and proc.pname = php-fpm
  # condition: evt.dir=< and container.id != host and proc.pname = php-fpm
  output: "PHP-fpm run execve in container (proc.ppid=%proc.ppid user=%user.name cmdline=%proc.cmdline proc.pcmdline=%proc.pcmdline evt.type=%evt.type fd.name=%fd.name proc.cwd=%proc.cwd proc.exeline=%proc.exeline %container.info parent=%proc.pname)"
  priority: ERROR
  tags: [users, container]
